version: '3'

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    environment:
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5678}
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:3000/api/integrations/manychat/webhook}
      - N8N_API_KEY=${N8N_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - SUPABASE_URL=${SUPABASE_URL:-}
      - SUPABASE_KEY=${SUPABASE_KEY:-}
    volumes:
      - n8n_data:/data
    restart: unless-stopped

volumes:
  n8n_data: